site_name: GraalVM Resources
theme:
  name: material
  palette: 
    scheme: default
    primary: deep purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
extra:
  analytics:
    provider: google
    property: G-D5MSF4CYKX
plugins:
  - social